### ISSUE TITLE
Failed to intercept cudaMalloc() in PyTorch

### ISSUE THREAD

**Issue by NicoleMayer** [zhuzilin/pytorch-malloc#2]
Hi,

I tried to run the profiler branch's code on my machine but failed to output Allocator related logs:

$ LD_PRELOAD=./libcudart.so python torch_example.py
start allocate 0
end allocate 0
start allocate 1
end allocate 1
start allocate 2
end allocate 2

Then I wrote an cuda program with cudaMalloc() and tried this library again and it works. So I wonder why this is happening, is it related to PyTorch's compilation?

**Comment by zhuzilin** [comment]
I just tried with the latest pytorch, it works fine, not sure what is happening in your situation...

**Comment by NicoleMayer** [comment]
@zhuzilin Maybe I should try other methods. Thanks for your reply anyway!
